# Generated by Django 4.0.1 on 2022-02-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0003_offenders1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offenders1',
            name='offenderID',
        ),
    ]
