# Generated by Django 4.0.1 on 2022-02-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0007_alter_offenders1_casestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offenders2',
            name='dateRelease',
        ),
        migrations.RemoveField(
            model_name='offenders2',
            name='dateTransfer',
        ),
    ]
