# Generated by Django 4.0.1 on 2022-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0016_alter_offenders2_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offenders2',
            name='password',
        ),
        migrations.AddField(
            model_name='offenders2',
            name='passwordDB',
            field=models.CharField(default='admin', max_length=8),
        ),
    ]
