# Generated by Django 4.0.1 on 2022-02-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0017_remove_offenders2_password_offenders2_passworddb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offenders2',
        ),
        migrations.AddField(
            model_name='offenders1',
            name='datenow',
            field=models.CharField(max_length=45, null=b'I00\n', verbose_name='datenow'),
            preserve_default=b'I00\n',
        ),
    ]
