# Generated by Django 4.0.1 on 2022-06-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0020_alter_offenders1_offenderpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='offenders1',
            name='complainant',
            field=models.CharField(max_length=45, null=b'I01\n', verbose_name='complainant'),
            preserve_default=b'I01\n',
        ),
    ]
