# Generated by Django 4.0.1 on 2022-02-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0002_remove_offenders_casedescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offenders1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offender', models.CharField(max_length=45, verbose_name='offender')),
                ('gender', models.CharField(max_length=6, verbose_name='gender')),
                ('age', models.IntegerField()),
                ('offenderID', models.CharField(max_length=4, null=b'I01\n', verbose_name='offenderID')),
                ('offense', models.CharField(max_length=45, verbose_name='offense')),
                ('caseStatus', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Release', 'Release'), ('Transfer', 'Transfer')], default='Ongoing', max_length=8)),
                ('caseDescription', models.TextField(max_length=400, null=b'I01\n', verbose_name='caseDescription')),
                ('password', models.CharField(max_length=12, verbose_name='password')),
                ('dateRelease', models.CharField(max_length=3)),
                ('dateTransfer', models.CharField(max_length=3)),
                ('dateComplaint', models.CharField(max_length=3)),
            ],
        ),
    ]
