# Generated by Django 4.0.1 on 2022-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0004_remove_offenders1_offenderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='offenders2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newpassword', models.CharField(max_length=12, verbose_name='newpassword')),
                ('password', models.CharField(max_length=12, verbose_name='password')),
                ('dateRelease', models.CharField(max_length=3)),
                ('dateTransfer', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='offenders',
        ),
        migrations.RemoveField(
            model_name='offenders1',
            name='dateRelease',
        ),
        migrations.RemoveField(
            model_name='offenders1',
            name='dateTransfer',
        ),
        migrations.RemoveField(
            model_name='offenders1',
            name='password',
        ),
    ]
