# Generated by Django 4.0.1 on 2022-02-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0009_alter_offenders2_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offenders2',
            name='newpassword',
        ),
    ]
