# Generated by Django 4.0.1 on 2022-05-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0018_delete_offenders2_offenders1_datenow'),
    ]

    operations = [
        migrations.AddField(
            model_name='offenders1',
            name='offenderPic',
            field=models.ImageField(blank=b'I01\n', null=b'I01\n', upload_to=''),
            preserve_default=b'I01\n',
        ),
    ]
