# Generated by Django 4.0.1 on 2022-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0021_offenders1_complainant'),
    ]

    operations = [
        migrations.AddField(
            model_name='offenders1',
            name='dateSchedule',
            field=models.CharField(max_length=45, null=b'I01\n', verbose_name='dateSchedule'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='offenders1',
            name='timeSchedule',
            field=models.CharField(max_length=45, null=b'I01\n', verbose_name='timeSchedule'),
            preserve_default=b'I01\n',
        ),
    ]
