# Generated by Django 4.0.1 on 2022-06-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0022_offenders1_dateschedule_offenders1_timeschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='offenders1',
            name='complainantEmail',
            field=models.EmailField(max_length=254, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
    ]
