# Generated by Django 4.0.1 on 2022-06-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0023_offenders1_complainantemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offenders1',
            name='offenderPic',
            field=models.ImageField(blank=b'I01\n', null=b'I01\n', upload_to='static/Media'),
        ),
    ]
