# Generated by Django 4.0.1 on 2022-07-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offenderLocatorApp', '0029_alter_offenders1_offenderpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offenders1',
            name='offenderPic',
        ),
    ]
